name: Build and Release Godot Game

on:
  push:
    branches:
      - main

jobs:
  build-windows-x64_64:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Download Godot
        run: |
          curl -L -o godot.zip https://github.com/godotengine/godot-builds/releases/download/4.5-dev3/Godot_v4.5-dev3_win64.exe.zip
          unzip godot.zip -d godot
          mv godot/Godot_v4.5-dev3_win64.exe godot/godot.exe

      - name: Download Export Templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/
          curl -L -o templates.zip https://github.com/godotengine/godot-builds/releases/download/4.5-dev3/Godot_v4.5-dev3_export_templates.tpz
          unzip templates.zip -d .
          mv templates ~/.local/share/godot/export_templates/4.5.dev3
          ls ~/.local/share/godot/export_templates/4.5.dev3

      - name: Export project
        run: |
          mkdir -p build/
          godot/godot.exe --export-release "Windows-x86_64" build/game.exe
          ls build/

      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-x64_64
          path: build/game.exe

  build-linux-x64_64:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true


      - name: Download Godot
        run: |
          curl -L -o godot.zip https://github.com/godotengine/godot-builds/releases/download/4.5-dev3/Godot_v4.5-dev3_linux.x86_64.zip
          unzip godot.zip -d godot
          chmod +x godot/Godot_v4.5-dev3_linux.x86_64

      - name: Download Export Templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/
          curl -L -o templates.zip https://github.com/godotengine/godot-builds/releases/download/4.5-dev3/Godot_v4.5-dev3_export_templates.tpz
          unzip templates.zip -d .
          mv templates ~/.local/share/godot/export_templates/4.5.dev3
          ls ~/.local/share/godot/export_templates/4.5.dev3

      - name: Export project
        run: |
          mkdir -p build
          godot/Godot_v4.5-dev3_linux.x86_64 --headless --export-release "Linux-x86_64" build/game.x86_64
          ls build/

      - name: Upload Linux build
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-x64_64
          path: build/game.x86_64

  build-macos-x64_64:
    name: Build for macOS
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Download Godot
        run: |
          curl -L -o godot.zip https://github.com/godotengine/godot-builds/releases/download/4.5-dev3/Godot_v4.5-dev3_macos.universal.zip
          unzip godot.zip -d godot
          chmod +x godot/Godot.app/Contents/MacOS/Godot

      - name: Download Export Templates
        run: |
          mkdir -p "~/Library/Application Support/Godot/export_templates/"
          curl -L -o templates.zip https://github.com/godotengine/godot-builds/releases/download/4.5-dev3/Godot_v4.5-dev3_export_templates.tpz
          unzip templates.zip -d .
          mv templates "~/Library/Application Support/Godot/export_templates/4.5.dev3"
          ls "~/Library/Application Support/Godot/export_templates/4.5.dev3"

      - name: Export project
        run: |
          ls /Users/runner/Library/Application\ Support/Godot/export_templates/4.5.dev3
          mkdir -p build/
          godot/Godot.app/Contents/MacOS/Godot --export-release "macOS-x86_64" build/game.dmg
          ls build/

      - name: Upload macOS build
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: build/game.dmg

  build-web:
    name: Build for Web
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Download Godot
        run: |
          curl -L -o godot.zip https://github.com/godotengine/godot-builds/releases/download/4.5-dev3/Godot_v4.5-dev3_linux.x86_64.zip
          unzip godot.zip -d godot
          chmod +x godot/Godot_v4.5-dev3_linux.x86_64

      - name: Download Export Templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/
          curl -L -o templates.zip https://github.com/godotengine/godot-builds/releases/download/4.5-dev3/Godot_v4.5-dev3_export_templates.tpz
          unzip templates.zip -d .
          mv templates ~/.local/share/godot/export_templates/4.5.dev3
          ls ~/.local/share/godot/export_templates/4.5.dev3

      - name: Export project
        run: |
          mkdir -p build/
          godot/Godot_v4.5-dev3_linux.x86_64 --headless --export-release "Web" build/web/
          ls build/
          ls build/web/

      - name: Upload Web build
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web/

  release-windows-x64_64:
    name: Release Windows Build
    needs: build-windows-x64_64
    runs-on: ubuntu-latest

    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-build

      - name: Create GitHub Release (Windows)
        id: create_release_windows
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Windows build to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release_windows.outputs.upload_url }}
          asset_path: build/game.exe
          asset_name: game-windows-x64_64.exe
          asset_content_type: application/octet-stream

  release-linux-x64_64:
    name: Release Linux Build
    needs: build-linux-x64_64
    runs-on: ubuntu-latest

    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-build

      - name: Create GitHub Release (Linux)
        id: create_release_linux
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Linux build to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release_linux.outputs.upload_url }}
          asset_path: build/game.x86_64
          asset_name: game-linux-x86_64.bin
          asset_content_type: application/octet-stream

  release-macos-x64_64:
    name: Release macOS Build
    needs: build-macos-x64_64
    runs-on: ubuntu-latest

    steps:
      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-build

      - name: Create GitHub Release (macOS)
        id: create_release_macos
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload macOS build to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release_macos.outputs.upload_url }}
          asset_path: build/game.dmg
          asset_name: game-macos-x64_64.dmg
          asset_content_type: application/octet-stream

  release-web:
    name: Release Web Build
    needs: build-web
    runs-on: ubuntu-latest

    steps:
      - name: Download Web artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build

      - name: Create GitHub Release (Web)
        id: create_release_web
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Web build to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release_web.outputs.upload_url }}
          asset_path: build/web/
          asset_name: game-web.zip
          asset_content_type: application/zip
