name: Build and Release Godot Game

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-windows-x86_64:
    name: Build for Windows x86_64
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Download Godot
        run: |
          curl -L -o godot.zip https://github.com/godotengine/godot-builds/releases/download/4.5-dev3/Godot_v4.5-dev3_win64.exe.zip
          unzip godot.zip -d godot
          ls godot

      - name: Download Export Templates
        run: |
          mkdir -p ~/AppData/Roaming/Godot/export_templates/
          curl -L -o templates.zip https://github.com/godotengine/godot-builds/releases/download/4.5-dev3/Godot_v4.5-dev3_export_templates.tpz
          unzip templates.zip -d .
          mv templates ~/AppData/Roaming/Godot/export_templates/4.5.dev3
          ls ~/AppData/Roaming/Godot/export_templates/4.5.dev3

      - name: Export project
        # The godot command runs in the background, so we need to wait for it to finish
        # before proceeding to the next step.
        run: |
          godot/Godot_v4.5-dev3_win64.exe --no-window --headless --verbose --export-release "Windows-x86_64" game.exe
          sleep 120

      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-x64_64
          path: game.exe

  build-linux-x86_64:
    name: Build for Linux x86_64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Download Godot
        run: |
          curl -L -o godot.zip https://github.com/godotengine/godot-builds/releases/download/4.5-dev3/Godot_v4.5-dev3_linux.x86_64.zip
          unzip godot.zip -d godot
          chmod +x godot/Godot_v4.5-dev3_linux.x86_64

      - name: Download Export Templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/
          curl -L -o templates.zip https://github.com/godotengine/godot-builds/releases/download/4.5-dev3/Godot_v4.5-dev3_export_templates.tpz
          unzip templates.zip -d .
          mv templates ~/.local/share/godot/export_templates/4.5.dev3

      - name: Export project
        run: |
          godot/Godot_v4.5-dev3_linux.x86_64 --headless --export-release "Linux-x86_64" game.x86_64

      - name: Upload Linux build
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-x64_64
          path: game.x86_64

  build-macos:
    name: Build for macOS
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Download Godot
        run: |
          curl -L -o godot.zip https://github.com/godotengine/godot-builds/releases/download/4.5-dev3/Godot_v4.5-dev3_macos.universal.zip
          unzip godot.zip -d godot
          chmod +x godot/Godot.app/Contents/MacOS/Godot

      - name: Download Export Templates
        run: |
          ls -d ~
          mkdir -p "/Users/runner/Library/Application Support/Godot/export_templates/"
          curl -L -o templates.zip https://github.com/godotengine/godot-builds/releases/download/4.5-dev3/Godot_v4.5-dev3_export_templates.tpz
          unzip templates.zip -d .
          mv templates "/Users/runner/Library/Application Support/Godot/export_templates/4.5.dev3"
          ls "/Users/runner/Library/Application Support/Godot/export_templates/4.5.dev3"

      - name: Export project
        run: |
          godot/Godot.app/Contents/MacOS/Godot --headless --export-release "macOS" game.dmg

      - name: Upload macOS build
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: game.dmg

  build-web:
    name: Build for Web
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Download Godot
        run: |
          curl -L -o godot.zip https://github.com/godotengine/godot-builds/releases/download/4.5-dev3/Godot_v4.5-dev3_linux.x86_64.zip
          unzip godot.zip -d godot
          chmod +x godot/Godot_v4.5-dev3_linux.x86_64

      - name: Download Export Templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/
          curl -L -o templates.zip https://github.com/godotengine/godot-builds/releases/download/4.5-dev3/Godot_v4.5-dev3_export_templates.tpz
          unzip templates.zip -d .
          mv templates ~/.local/share/godot/export_templates/4.5.dev3
          ls ~/.local/share/godot/export_templates/4.5.dev3

      - name: Export project
        run: |
          mkdir -p build/web
          godot/Godot_v4.5-dev3_linux.x86_64 --headless --export-release "Web" build/web/index

      - name: Replace variables in exported HTML
        run: |
          sed -i 's/\$GODOT_PROJECT_NAME/my-rts-game-godot/g' build/web/index.html
          sed -i 's/\$GODOT_SPLASH_COLOR/#242424/g' build/web/index.html
          sed -i 's/\$GODOT_SPLASH_CLASSES/show-image--true fullsize--true use-filter--true/g' build/web/index.html
          sed -i 's/\$GODOT_SPLASH/index.png/g' build/web/index.html
          sed -i 's/\$GODOT_URL/index.js/g' build/web/index.html
          sed -i 's/\$GODOT_CONFIG/{"args":[],"canvasResizePolicy":2,"ensureCrossOriginIsolationHeaders":false,"executable":"index","experimentalVK":false,"fileSizes":{"index.pck":15160112,"index.wasm":47811600},"focusCanvas":true,"gdextensionLibs":[],"serviceWorker":"index.service.worker.js"}/g' build/web/index.html
          sed -i 's/\$GODOT_THREADS_ENABLED/false/g' build/web/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
